
import { GoogleGenAI, Type, Modality } from "@google/genai";
import { ImageStyle, GeneratedResult, SocialContent, MarketingAdvice, VideoStoryboard } from "../types";
import { SOCIAL_PLATFORMS } from "../constants";

// الحصول على نسخة جديدة لضمان استخدام أحدث مفتاح API تم اختياره
const getAI = () => new GoogleGenAI({ apiKey: process.env.API_KEY });

// Audio Helper: Manual decode from base64 (as per guidelines)
function decode(base64: string) {
  const binaryString = atob(base64);
  const len = binaryString.length;
  const bytes = new Uint8Array(len);
  for (let i = 0; i < len; i++) {
    bytes[i] = binaryString.charCodeAt(i);
  }
  return bytes;
}

// Audio Helper: Add WAV header to raw PCM bytes
function getWavHeader(dataLength: number, sampleRate: number, numChannels: number, bitsPerSample: number) {
  const header = new ArrayBuffer(44);
  const view = new DataView(header);
  view.setUint32(0, 0x52494646, false); // "RIFF"
  view.setUint32(4, 36 + dataLength, true);
  view.setUint32(8, 0x57415645, false); // "WAVE"
  view.setUint32(12, 0x666d7420, false); // "fmt "
  view.setUint32(16, 16, true);
  view.setUint16(20, 1, true); // PCM
  view.setUint16(22, numChannels, true);
  view.setUint32(24, sampleRate, true);
  view.setUint32(28, sampleRate * numChannels * (bitsPerSample / 8), true);
  view.setUint16(32, numChannels * (bitsPerSample / 8), true);
  view.setUint16(34, bitsPerSample, true);
  view.setUint32(36, 0x64617461, false); // "data"
  view.setUint32(40, dataLength, true);
  return header;
}

/**
 * تحويل الملف إلى base64
 */
export const fileToBase64 = (file: File): Promise<string> => {
  return new Promise((resolve, reject) => {
    const reader = new FileReader();
    reader.readAsDataURL(file);
    reader.onload = () => {
      const base64String = reader.result?.toString().split(',')[1];
      if (base64String) resolve(base64String);
      else reject(new Error("Failed to convert file to base64"));
    };
    reader.onerror = error => reject(error);
  });
};

/**
 * معالجة الصورة لاستبدال الخلفية
 */
export const processSweetImage = async (
  originalBase64: string,
  style: ImageStyle
): Promise<GeneratedResult> => {
  const ai = getAI();
  const modelName = 'gemini-2.5-flash-image';
  
  try {
    const response = await ai.models.generateContent({
      model: modelName,
      contents: {
        parts: [
          {
            inlineData: {
              data: originalBase64,
              mimeType: 'image/png',
            },
          },
          {
            text: `Keep the central dessert item exactly as it is. Replace the entire background with: ${style.prompt}. Ensure natural lighting, realistic shadows, and professional food photography quality.`,
          },
        ],
      },
    });

    let imageUrl = '';
    if (response.candidates?.[0]?.content?.parts) {
      for (const part of response.candidates[0].content.parts) {
        if (part.inlineData) {
          imageUrl = `data:image/png;base64,${part.inlineData.data}`;
          break;
        }
      }
    }

    if (!imageUrl) {
      throw new Error("No image generated by the model");
    }

    return {
      styleId: style.id,
      imageUrl
    };
  } catch (error) {
    console.error("Error processing style", style.id, error);
    throw error;
  }
};

/**
 * توليد نصوص تسويقية باللهجة الجزائرية
 */
export const generateSocialCaptions = async (styleName: string): Promise<Record<string, string>> => {
  const ai = getAI();
  const model = 'gemini-3-flash-preview';
  const prompt = `أنت خبير تسويق حلويات في الجزائر. قم بكتابة نصوص تسويقية جذابة جداً باللهجة الجزائرية (الدارجة الجزائرية) لقطعة حلوى تم تصويرها في بيئة "${styleName}".
  استخدم كلمات جزائرية دارجة محببة (مثل: "بنينة"، "تقتل"، "حاجة فور"، "ارواحو تذوقو") لجذب الزبائن الجزائريين.
  أريد 5 نصوص مخصصة للمنصات التالية: Instagram Post, Instagram Story, Facebook, TikTok, Snapchat.
  أرجع النتيجة بتنسيق JSON حصراً بالمفاتيح: insta_post, insta_story, facebook, tiktok, snapchat.`;

  const response = await ai.models.generateContent({
    model: model,
    contents: prompt,
    config: {
      responseMimeType: "application/json",
      responseSchema: {
        type: Type.OBJECT,
        properties: {
          insta_post: { type: Type.STRING },
          insta_story: { type: Type.STRING },
          facebook: { type: Type.STRING },
          tiktok: { type: Type.STRING },
          snapchat: { type: Type.STRING },
        },
        required: ["insta_post", "insta_story", "facebook", "tiktok", "snapchat"]
      }
    }
  });

  return JSON.parse(response.text || '{}');
};

/**
 * توليد نصيحة تسويقية باللهجة الجزائرية
 */
export const generateMarketingAdvice = async (styleName: string): Promise<MarketingAdvice> => {
  const ai = getAI();
  const model = 'gemini-3-flash-preview';
  const prompt = `أنت مستشار تسويق رقمي في الجزائر. قمنا بتصوير قطعة حلوى بخلفية "${styleName}".
  قدم لنا:
  1. نصيحة تسويقية ذكية (tip) لزيادة المبيعات في السوق الجزائري.
  2. مجموعة وسوم (hashtags) قوية ونشطة في الجزائر للحلويات.
  3. رسالة واتساب (whatsappMessage) جاهزة يرسلها الزبون للبائع لطلب المنتج بالدارجة الجزائرية.
  
  أرجع النتيجة بتنسيق JSON حصراً.`;

  const response = await ai.models.generateContent({
    model: model,
    contents: prompt,
    config: {
      responseMimeType: "application/json",
      responseSchema: {
        type: Type.OBJECT,
        properties: {
          tip: { type: Type.STRING },
          hashtags: { type: Type.STRING },
          whatsappMessage: { type: Type.STRING }
        },
        required: ["tip", "hashtags", "whatsappMessage"]
      }
    }
  });

  return JSON.parse(response.text || '{}');
};

/**
 * توليد فيديو ترويجي من صورة
 */
export const generatePromoVideo = async (imageUri: string): Promise<string> => {
  const ai = getAI();
  const base64Data = imageUri.split(',')[1];
  
  let operation = await ai.models.generateVideos({
    model: 'veo-3.1-fast-generate-preview',
    prompt: 'Cinematic slow zoom into the dessert, soft lighting, professional food commercial style, high quality product animation',
    image: {
      imageBytes: base64Data,
      mimeType: 'image/png',
    },
    config: {
      numberOfVideos: 1,
      resolution: '720p',
      aspectRatio: '9:16'
    }
  });

  while (!operation.done) {
    await new Promise(resolve => setTimeout(resolve, 10000));
    operation = await ai.operations.getVideosOperation({ operation: operation });
  }

  const downloadLink = operation.response?.generatedVideos?.[0]?.video?.uri;
  const response = await fetch(`${downloadLink}&key=${process.env.API_KEY}`);
  const blob = await response.blob();
  return URL.createObjectURL(blob);
};

/**
 * توليد تعليق صوتي (TTS)
 */
export const generatePromoAudio = async (text: string): Promise<string> => {
  const ai = getAI();
  const response = await ai.models.generateContent({
    model: "gemini-2.5-flash-preview-tts",
    contents: [{ parts: [{ text: `Say warmly and enthusiastically in Arabic (Algerian dialect): ${text}` }] }],
    config: {
      responseModalities: [Modality.AUDIO],
      speechConfig: {
        voiceConfig: {
          prebuiltVoiceConfig: { voiceName: 'Kore' },
        },
      },
    },
  });

  const base64Audio = response.candidates?.[0]?.content?.parts?.[0]?.inlineData?.data;
  if (!base64Audio) throw new Error("Audio generation failed");

  const audioBytes = decode(base64Audio);
  const wavHeader = getWavHeader(audioBytes.length, 24000, 1, 16);
  const wavBlob = new Blob([wavHeader, audioBytes], { type: 'audio/wav' });
  return URL.createObjectURL(wavBlob);
};

/**
 * توليد مخطط فيديو (Storyboard)
 */
export const generateVideoStoryboard = async (styleName: string): Promise<VideoStoryboard> => {
  const ai = getAI();
  const model = 'gemini-3-flash-preview';
  const prompt = `أنت مخرج إعلانات محترف. قم بإنشاء مخطط فيديو (Storyboard) إعلاني لقطعة حلوى في بيئة "${styleName}".
  أريد 3 مشاهد، كل مشهد يحتوي على:
  1. وصف بصري (visualDescription) بالإنجليزية للمصمم.
  2. تعليق صوتي (voiceover) بالدارجة الجزائرية.
  3. مدة المشهد (duration).
  
  أرجع النتيجة بتنسيق JSON حصراً.`;

  const response = await ai.models.generateContent({
    model: model,
    contents: prompt,
    config: {
      responseMimeType: "application/json",
      responseSchema: {
        type: Type.OBJECT,
        properties: {
          scenes: {
            type: Type.ARRAY,
            items: {
              type: Type.OBJECT,
              properties: {
                id: { type: Type.INTEGER },
                duration: { type: Type.STRING },
                visualDescription: { type: Type.STRING },
                voiceover: { type: Type.STRING }
              },
              required: ["id", "duration", "visualDescription", "voiceover"]
            }
          }
        },
        required: ["scenes"]
      }
    }
  });

  return JSON.parse(response.text || '{"scenes":[]}');
};

/**
 * تغيير حجم الصورة للقص المنصات
 */
export const resizeAndCropImage = (
  base64: string, 
  targetWidth: number, 
  targetHeight: number
): Promise<string> => {
  return new Promise((resolve) => {
    const img = new Image();
    img.onload = () => {
      const canvas = document.createElement('canvas');
      canvas.width = targetWidth;
      canvas.height = targetHeight;
      const ctx = canvas.getContext('2d');
      if (!ctx) return resolve(base64);

      const sourceAspect = img.width / img.height;
      const targetAspect = targetWidth / targetHeight;

      let drawWidth, drawHeight, offsetX, offsetY;

      if (sourceAspect > targetAspect) {
        drawHeight = img.height;
        drawWidth = img.height * targetAspect;
        offsetX = (img.width - drawWidth) / 2;
        offsetY = 0;
      } else {
        drawWidth = img.width;
        drawHeight = img.width / targetAspect;
        offsetX = 0;
        offsetY = (img.height - drawHeight) / 2;
      }

      ctx.drawImage(img, offsetX, offsetY, drawWidth, drawHeight, 0, 0, targetWidth, targetHeight);
      resolve(canvas.toDataURL('image/png'));
    };
    img.src = base64;
  });
};
